version: '3.7'
services:
  exporter:
    image: kibatic-exporter
    container_name: kibatic-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:metrics.domain.tld